version: "3"

services:
  ia10-ui:
    build:
      context: ./packages/ia10-ui
      dockerfile: Dockerfile
      target: dev
    command: yarn dev
    hostname: ia10-ui
    volumes:
      - ./packages/ia10-ui:/app
      - ia10_ui_node_modules:/app/node_modules
    ports:
      - 8100:3000

volumes:
  ia10_ui_node_modules:
