#!/usr/bin/env bash

set -eu

cd "$(dirname "$(cd "$(dirname "${BASH_SOURCE:-$0}")" && pwd)")"

docker-compose down

(cd packages/ia10-ui && rm -rf node_modules node_modules_tmp)

docker-compose build ui

OPTS=-T ./scripts/attach-ui <<EOL
yarn
tar zcvf node_modules_tmp node_modules > /dev/null
EOL

cd packages/ia10-ui

tar zxf node_modules_tmp > /dev/null
rm -rf node_modules_tmp
